In [3]:
import numpy as np


In [4]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
arr2=np.array([[1,2,3],[6,7,8]])
print(arr2)

[[1 2 3]
 [6 7 8]]


In [6]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
ar=np.ones((3,5))
print(ar)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.arange(1,10,3)

array([1, 4, 7])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [2]:
arr=np.array([[1,2,3,7],[4,5,6,7],[7,8,9,7]])
arr

NameError: name 'np' is not defined

In [33]:
arr.shape

(3, 4)

In [34]:
arr.size

12

In [5]:
print(arr.dtype)

int64


In [37]:
arr.ndim

2

In [51]:
arr=np.array([[1,2,3,7],[4,5,6,7],[7,8,9,7]],dtype='float64')
arr

array([[1., 2., 3., 7.],
       [4., 5., 6., 7.],
       [7., 8., 9., 7.]])

In [57]:
arr=np.array([[1,2,3,7],[4,5,6,7],[7,8,9,7]],dtype='float32')
arr

array([[1., 2., 3., 7.],
       [4., 5., 6., 7.],
       [7., 8., 9., 7.]], dtype=float32)

In [59]:
arr.dtype

dtype('float32')

In [60]:
ap=arr.astype('float32') # data type conversion

In [61]:
ap.dtype

dtype('float32')

In [63]:
arr=np.array([1,2,3,7,4,6,8,2])
arr.reshape(2,4)

array([[1, 2, 3, 7],
       [4, 6, 8, 2]])

In [64]:
arr=np.array([[1,2,3,7],[4,5,6,7],[7,8,9,7]])
arr.reshape(4,3)

array([[1, 2, 3],
       [7, 4, 5],
       [6, 7, 7],
       [8, 9, 7]])