In [1]:
import numpy as np

In [4]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
flat=arr.flatten()

In [13]:
print(flat)

[1 2 3 4 5 6 7 8 9]


In [8]:
print(flat[-1])

9


In [12]:
print(flat[1:2])

[2]


In [14]:
print(flat[:5])

[1 2 3 4 5]


In [15]:
print(flat[::2])

[1 3 5 7 9]


In [16]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b=flat[1:5]
b#it return view

array([343,   3,   4,   5])

In [19]:
b[0]=343

In [20]:
flat

array([  1, 343,   3,   4,   5,   6,   7,   8,   9])

In [26]:
c=flat[:3].copy()#it create copy not affect original array
c

array([  1, 343,   3])

In [24]:
c[0]=45

In [25]:
flat

array([  1, 343,   3,   4,   5,   6,   7,   8,   9])

FANCY INDEXING

In [27]:
arr1=np.array([1,2,3,4,5,6,7])

In [29]:
arr1[[1,2,3]]# at one index ,2 index,3 index it gives value

array([2, 3, 4])

In [30]:
arr2=arr1>4

In [31]:
arr2

array([False, False, False, False,  True,  True,  True])

In [35]:
arr1[arr1>4] # or arr1[arr2]

array([5, 6, 7])

In [36]:
arr1[arr2]

array([5, 6, 7])