In [1]:
import numpy as np

In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9,]])

In [4]:
arr.shape

(3, 3)

In [6]:
arr2=np.array([1.1,2.2,3.3],dtype='int')

In [7]:
arr2

array([1, 2, 3])

In [9]:
arr3=np.array([1,2,3,4,5,6])
print(arr3[arr3%2==0])

[2 4 6]


In [11]:
print(arr3[[1,3,5]])

[2 4 6]


In [12]:
arr4=np.array([1,2,3,4,5,6,7,8,9])
arr4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr5=np.array([23,56,34,98,54,24,49,25,43,99,50])


In [20]:
print(arr5[arr5>50])

[56 98 54 99]
