In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
arr[:,0]# first column

array([1, 4, 7])

In [35]:
arr[0]#it display first row

array([1, 2, 3])

In [36]:
np.sum(arr,axis=0)#sum along the row(move down to the column

array([12, 15, 18])

In [25]:
np.sum(arr,axis=1)#sum along the column(move along each row)

array([ 6, 15, 24])

In [13]:
print(arr[0][1])#first row number nad second column number

2


In [16]:
print(arr[0,1])# take '0' th row and take index '1' column

2


In [38]:
arr[0][0]=0

In [39]:
print(arr)

[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [19]:
print(arr[1:2,2:3]) # it represent left side comma row , right side of comma column

[[6]]


In [20]:
print(arr[1,2])

6


In [23]:
print(arr[0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
arr3d=np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])

In [37]:
print(arr3d[:,0,:])#selecting first row of each sheet

[[1 2 3]
 [7 8 9]]


In [31]:
print(arr3d[1:,1,:])

[[10 11 12]]


In [32]:
arr3d[:,0]

array([[1, 2, 3],
       [7, 8, 9]])

In [40]:
arr3d[:,0,:]=0

In [41]:
print(arr3d)

[[[ 0  0  0]
  [ 4  5  6]]

 [[ 0  0  0]
  [10 11 12]]]
