In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
result=arr+10 # broadcasting 10 is added to all element 
print(result)


[11 12 13 14 15]


In [5]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2,3])

In [8]:
print(arr1+arr2)
print(arr1-arr2)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
